### ISSUE TITLE
AiMesh Support

### ISSUE THREAD

**Issue by Akyfire** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#1]
Features don't work on devices connected to AiMesh nodes

**Comment by jumpsmm7** [comment]
works for me.

**Comment by jumpsmm7** [comment]
Also, Let it be noted that if you are trying to use AdGuardHome as a DHCP server, this will not work for AiMesh nodes. You must use adguardhome strictly as dns only. There is nothing I can do to make the DHCP server on AdGuardHome work for AiMesh since that is an integral part of Asus and not the latter.

**Comment by jumpsmm7** [comment]
I pushed a DHCP fix, some users were reporting DHCP issues. That might suggest your aimesh problems will go away to. 
Please test and let me know.

**Comment by Akyfire** [comment]
> I pushed a DHCP fix, some users were reporting DHCP issues. That might suggest your aimesh problems will go away to. 
> Please test and let me know.
> 

That has fixed the issue! Brilliant! 👍🏻
