### ISSUE TITLE
Is it possible to allow external access the adguard dashboard?

### ISSUE THREAD

**Issue by geneliu** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#108]
Thanks very much for the Nice Job!!

I setup adguardhome with this installer successfully on my asus router. 
I usually use another workstation connect direct to up level network (WAN) via a network cable. So the computer is external from the asus wireless router (LAN). Whenever I want to access the adguardHome dashboard I have to switch to wifi which has wifi routers internal ip. 

I wonder if there is a setting to let the dashboard (http://router-ip:14711) be accessible from it WAN ip?

**Comment by jumpsmm7** [comment]
Yes you can enable WAN access, but you will have to setup the necessary IPtable rules your self. An example of such rule is:

`iptables -I INPUT -p tcp -m tcp --dport 14711 -j ACCEPT`

While such is possible, this is highly discourage for the security implications it imposes. You would place this rule in a firewall-start script within JFFS. This is placed on your end to configure because the only aim of this script is to "install" adguardhome on asuswrt-merlin firmware asus routers.

**Comment by geneliu** [comment]
Thank you!!
