### ISSUE TITLE
ipv6 address lost

### ISSUE THREAD

**Issue by shugo-chara** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#118]
Thanks for your work, it has been working fine on my AX-82u. 
Until I changed a setting and found that the ipv6 address was missing.
![image](https://user-images.githubusercontent.com/20610965/153825814-bc1cce6e-e1e0-4556-a4f7-493e783037a2.png)
![image](https://user-images.githubusercontent.com/20610965/153826052-088e5d42-6faf-4c6d-b064-c04da510e2ee.png)

![image](https://user-images.githubusercontent.com/20610965/153826108-8583fa57-80c1-4a7d-927d-d6acc551f7bc.png)
![image](https://user-images.githubusercontent.com/20610965/153826331-2ba16269-9b1d-4222-aa20-a68d7f82c5e8.png)

dns：8.8.8.8，1.1.1.1
AX-82U merlin 3.0.0.4.386

log：
[log.zip](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/files/8059069/log.zip)

**Comment by jumpsmm7** [comment]
> Thanks for your work, it has been working fine on my AX-82u. Until I changed a setting and found that the ipv6 address was missing. ![image](https://user-images.githubusercontent.com/20610965/153825814-bc1cce6e-e1e0-4556-a4f7-493e783037a2.png) ![image](https://user-images.githubusercontent.com/20610965/153826052-088e5d42-6faf-4c6d-b064-c04da510e2ee.png)
> 
> ![image](https://user-images.githubusercontent.com/20610965/153826108-8583fa57-80c1-4a7d-927d-d6acc551f7bc.png) ![image](https://user-images.githubusercontent.com/20610965/153826331-2ba16269-9b1d-4222-aa20-a68d7f82c5e8.png)
> 
> dns：8.8.8.8，1.1.1.1 AX-82U merlin 3.0.0.4.386
> 
> log： [log.zip](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/files/8059069/log.zip)
@shugo-chara
Thank you for pointing this out, this may be a good topic for you to post on the SNBforums as this is a custom option a user would/could make, however, ipv4 DNS can often times resolve both A and AAAA request and it should be allowed to if able. Otherwise sites that may only be resolvable VIA AAAA configurations may not be available and some users internet may otherwise be broken  by disabling AAAA request being disabled. However, this is not an issue of this installer. This installer does everything it is intended to do, which is install AdGuardHome to Asuswrt-Merlin routers.
