### ISSUE TITLE
After installing AdGuard it get lost and becomes impossible to load

### ISSUE THREAD

**Issue by b255ea006** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#185]
https://github.com/AdguardTeam/AdGuardHome/issues/5459#issue-1572689749

I have reported an issue and became the advice to contact you here.

Please view Link above.

Regards

**Comment by jumpsmm7** [comment]
Can you please proved me with the appropriate files using these directions:
https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#how-to-report-issue

Or, provide the contents of each file being requested either here or on pastebin. 
Whatever is easier for you. 

I also need to know what model router you are using. And what lists you are trying to load.

**Comment by jumpsmm7** [comment]
> [AdguardTeam/AdGuardHome#5459 (comment)](https://github.com/AdguardTeam/AdGuardHome/issues/5459#issue-1572689749)
> 
> I have reported an issue and became the advice to contact you here.
> 
> Please view Link above.
> 
> Regards

Most likely one of three things is occurring(or a combination of the three), too many filters are selected for your router to RAM to handle, the flash storage being used it not in great condition, and/ or your dns settings are not configured correctly. For further troubleshooting. I recommend asking advice in the snbforum since this is not a direct issue I can solve here since it does not relate to the actual installing of AGH and relates more to how you have your setup configured:

https://www.snbforums.com/forums/asuswrt-merlin-addons.60/
