### ISSUE TITLE
Compatibility of these settings when Adguard Home is installed

### ISSUE THREAD

**Issue by privacyguy123** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#194]
Is there any recommendation to avoid possible breakage?

![image](https://github.com/jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer/assets/50337995/cedf9c20-17ef-4f77-a1f7-beb14f0e43da)

**Comment by privacyguy123** [comment]
I'll keep all my questions in one issue perhaps - do you know what is causing this spam?

```
AdGuardHome[3574]: 2023/10/02 14:08:16.039240 [error] dnsproxy: unpacking udp packet: dns: buffer size too small
```

**Comment by jumpsmm7** [comment]
> Is there any recommendation to avoid possible breakage?
> 
> ![image](https://user-images.githubusercontent.com/50337995/271850597-cedf9c20-17ef-4f77-a1f7-beb14f0e43da.png)

Dont worry about these because dns validation is no longer being done by dnsmasq, so these options are pointless when running adguardhome. Only adjust DNS settings in the AdGuardHome GUI, or AdGuardHome WebUI. The only setting that will be helpful in the image above is setting Auto DoH to "yes" so your Newer Web Browsers do not attempt to override AdGuardHomes DNS.
