### ISSUE TITLE
AdGuard has become very unstable after recent versions

### ISSUE THREAD

**Issue by francoism90** [jumpsmm7/Asuswrt-Merlin-AdGuardHome-Installer#215]
AdGuard has become very unstable for me, and I don't know why.

It seems AdGuard freezes and a reboot of the router doesn't always fix it.
I'm having trouble debugging this issue, but I think the DHCP of the ISP is the one to blame (modem in bridge-mode, and is recently changed), and this causes AdGuard to become unstable/unusable because it cannot reach the configured upstream server(s).

So far, I've tried completely removing AdGuard (incl. configuration), but it keeps happening. I've also added IPv6-addresses and such, but this doesn't make any difference.

AdGuard version: v0.107.43
Merlin/Device: 3004.388.6 - ASUS RT-AX58U

How may I provide you with debug code/investigate this?
The router doesn't crash, so I can ssh to the console.

Thanks, also for maintaining this.

**Comment by jumpsmm7** [comment]
Have you tried reducing the size of your filter lists? That is one suggestion I could come up with. I have never been able to find out the whole "DHCP of ISP" concern. I have a cable modem that does not have to be placed in "bridge-mode" to act as the modem for my router. My router always receives an IP address assigned from the modem & ISP (think it is based on hardware mac-address of router because it only changes if I change routers or mac-addr). If it was working before, and now isn't- either you have changed something inside the AGH configuration that is making it unstable (like using too many filters), or something has changed with the way your ISP is handling your configuration. IF it is an ISP issue, I do not see your internet working well with any configuration because the ISP is the gatekeeper. If the ISP is causing connection breaks, the same will happen with or without AGH running. Another possibility is, you may need to add more DNS servers to your AGH upstream DNS section. it could be that AGH is not able to get a response from your current AGH upstream servers list.   You may need to add more servers for redundancies sake.

**Comment by jumpsmm7** [comment]
> AdGuard has become very unstable for me, and I don't know why.
> 
> It seems AdGuard freezes and a reboot of the router doesn't always fix it. I'm having trouble debugging this issue, but I think the DHCP of the ISP is the one to blame (modem in bridge-mode, and is recently changed), and this causes AdGuard to become unstable/unusable because it cannot reach the configured upstream server(s).
> 
> So far, I've tried completely removing AdGuard (incl. configuration), but it keeps happening. I've also added IPv6-addresses and such, but this doesn't make any difference.
> 
> AdGuard version: v0.107.43 Merlin/Device: 3004.388.6 - ASUS RT-AX58U
> 
> How may I provide you with debug code/investigate this? The router doesn't crash, so I can ssh to the console.
> 
> Thanks, also for maintaining this.

Adguardhome isn't compatible with scribe script if you are running the two together. This is because scribe uses syslog-ng. Adguardhome has a hard time using syslog-ng on AX models. If you uninstall scribe. Your issue with adguard home will go away.

**Comment by francoism90** [comment]
@jumpsmm7 I did some more testing, and it turns out it's not only AdGuard crashing, also Diversion for example. However, it seems AdGuard goes down when the WAN isn't working, I don't think this is correct behavior?

I think I should report this upstream, as it's the router and modem not being able to exchange a DHCP-lease. This causes the router to corrupt the route-table, and keep looping.

**Comment by francoism90** [comment]
@jumpsmm7 Hopefully also helpful for others, the issue seems to be IPv6 related. After changing to `Stateful`, the issue seems to be gone.

From what I've read, this seems to be an Android issue. Stateful has some disadvantages, but overal it seems to working fine now. :)
